credentials:
  usernames:
    joaodorea:
      email: joaodorea300@gmail.com
      logged_in: False
      name: Joao Dorea
      password: joao1234
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name